import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button, ButtonGroup } from "@chakra-ui/react"
import { Provider } from "@/components/ui/provider"
import { Box, Flex } from "@chakra-ui/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning>
      <Provider>
        <Box as="header" bg="gray.50" px={6} py={4} boxShadow="md">
          <Flex align="center" justify="space-between">
            <Box fontWeight="bold" fontSize="xl" color="teal.600">
              Taxi Marseille
            </Box>
            <ButtonGroup spacing={4}>
              <Button colorScheme="teal">Замовити таксі</Button>
              <Button variant="outline" colorScheme="teal">Список поїздок</Button>
            </ButtonGroup>
          </Flex>
        </Box>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
        </body>
      </Provider>
    </html>
  );
}
