import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button, ButtonGroup } from "@chakra-ui/react"
import { Provider } from "@/components/ui/provider"
import { Box, Flex } from "@chakra-ui/react";
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning>
      <Provider>
        <Box as="header" bg="gray.50" px={6} py={4} boxShadow="md">
          <Flex align="center" justify="space-between">
            <Box fontWeight="bold" fontSize="xl" color="teal.600">
              Taxi Marseille
            </Box>
            <ButtonGroup spacing={4}>
              <Link prefetch={false} href="/" passHref style={{ textDecoration: 'none' }}>
                <Box
                  as="span"
                  px={4}
                  py={2}
                  borderRadius="md"
                  bg="teal.500"
                  color="white"
                  fontWeight="semibold"
                  boxShadow="sm"
                  _hover={{ bg: 'teal.600', textDecoration: 'none' }}
                  transition="background 0.2s"
                  cursor="pointer"
                  mr={2}
                >
                  Замовити таксі
                </Box>
              </Link>
              <Link prefetch={false} href="/trip-list" passHref style={{ textDecoration: 'none' }}>
                <Box
                  as="span"
                  px={4}
                  py={2}
                  borderRadius="md"
                  bg="white"
                  color="teal.600"
                  fontWeight="semibold"
                  border="2px solid"
                  borderColor="teal.500"
                  boxShadow="sm"
                  _hover={{ bg: 'gray.100', textDecoration: 'none' }}
                  transition="background 0.2s"
                  cursor="pointer"
                >
                  Список поїздок
                </Box>
              </Link>
            </ButtonGroup>
          </Flex>
        </Box>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
        </body>
      </Provider>
    </html>
  );
}
